### ISSUE TITLE
DB 모델링 수정

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/s-mall#11]
[ Context ]
- 기획의 내용이 광범위함에 따라 DB 모델링 또한 사이즈가 커졌다. 기획을 수정 후, DB 의 내용 또한 재점검할 필요성이 생겼다.

[ Definition of Done  ] 
- 각 관계도에 대해 설명 첨부 
- 각 칼럼등을 전체적으로 점검 후 수정 필요한 내용 수정
- pk ( auto-increment ) 는 필수적으로 지정

[ Ref ]
- https://www.erdcloud.com/d/pGTMqeeDb54xjn7nj

**Comment by f-lab-robert** [comment]
https://www.erdcloud.com/d/pGTMqeeDb54xjn7nj

**Comment by f-lab-robert** [comment]
- 아래 관계에 대한 설명도 있으면 좋을 것 같습니다

![스크린샷 2022-04-16 오후 11 00 46](https://user-images.githubusercontent.com/84081620/163677791-9e4e4d94-0b88-47f7-b867-fd0a59263169.png)

**Comment by KJW921222** [comment]
DB 모델링 수정 및 Wiki 작성 완료

**Comment by f-lab-robert** [comment]
@KJW921222 리뷰를 위해 위에 issue 에 등록된 문제점들을 어떻게 풀었는지 issue 에 설명을 남겨주셔야 합니다.

**Comment by f-lab-robert** [comment]
> https://www.erdcloud.com/d/pGTMqeeDb54xjn7nj

위의 내용에 대한 추가적인 질문입니다. 이 부분 또한 검토해봐주세요.

1. created_by, modifed_by 를 "user 의 이름" 이 아닌 "id" 로 지정해 놓으면 유저의 정보를 어떻게 추출해오실 예정일까요 ?
2. Orders table 등 부분적으로 위의 값들이 보이지 않는 table 이 있는데 왜 제외하신걸까요 ? 주문의 시점과 주문 상태의 변경에 대한 정보는 tracking 하지 않아도 되나요 ?
3. date, datetime, timestamp 등은 다 고려해보시고 속성을 정하신걸까요 ?
4. orderItem 과 item 간의 관계가 저번에는 맺어져있지 않았는데 이번주에는 맺어져있습니다. 그 이유가 무엇일까요 ? 반대로 orderItem 과 itemDetail 의 관계가 사라진 이유는 무엇일까요 ?
5. orderItem table 의 명칭은 ordersItem 대신에 orderItem 으로 선정하신 이유가 있으실까요 ?
6. camel case 대신 현재 네이밍을 선택해서 얻을 수 있는 이점이 무엇이 있을까요 ?
7. 특정 table 들의 id 는 테이블 명칭_id 이면서 어떤 테이블들은 또 id 로 되어있습니다. 통일성을 지키는게 좋지 않을까요 ?
8. 회원가입을 고려해보면 user_id, pwd 등은 필수인거 같은데 왜 null 이 허용되도록 설계하셨을까요 ? 
9. small 은 배송에 대해 다루지 않습니다. 때문에 주문에 대한 상태가 있지만 실질적으로 주문 완료 밖에 현 상태에는 없다는 것도 기획서나 DB modeling 설명에 기재되어야 하지 않을까요 ? 제 3자가 어떻게 이 부분을 알 수 있을까요 ? 

위의 내용들을 리뷰해보시고 더 나아가서 더 많은 고민들을 통해 문제점이나 개선 사항등을 찾아보시겠어요 ?

**Comment by KJW921222** [comment]
1. member 테이블을 참조할 생각이었는데 닉네임, 성명 같은 필드가 없으므로 created_by, modifed_by를 pk인 id 필드 값 대신 실제 user가 사용하는 userid 필드를 등록하도록 변경
2. 

- orders 테이블 : 주문은 본인이 하는 것이니 created_by에 member_id를 사용하고, 주문일자가 곧 created_date이므로 order_date 필드를 생성했습니다. 주문 상태 변경 추적을 위해  modified_date 필드를 추가했습니다.  
- item_detail, item_image 테이블 :  item 테이블에 종속된 테이블은 item이 가지고 있으므로 필요하지 않다고 생각했습니다. 
- item_category 테이블 : item_category 테이블은 item의 created, modified 정보와는 구분되어야 한다고 생각하여 해당 필드들을 추가했습니다.
3. 주문 등은 일자가 아닌 시간에 대한 정보까지 갖고 있어야한다고 생각해서 datetime과 timestamp 중 택일하기로 했는데, 국내 서비스에 한정할 것이므로 datetime을 선택하였습니다.
4. order_Item - item : 의미상 주문이 해당 물건(item)을 갖는게 맞다고 판단하는데  주문 item의 사이즈를 알수 없다는 문제점이 있습니다.
해결 방안으로 order_item과 item_detail에 관계를 맺는 방법과 order_item과 item이 관계를 맺고 item_detail과도 관계를 맺는 방법 2가지를 생각해보았습니다. 어떻게 관계를 맺어야할지 판단하기 어려워 약간의 조언을 부탁드리고 싶습니다.
5.  개념적으로는 order이지만 db예약어를 피하기 위해 테이블명을 orders로 결정했습니다. 
6. db 필드명은 대소문자 구분을 하지 않기 때문에 camel case보다 필드명을 보고 무슨 정보를 가지는 필드인지 명확하게  표현하기 유리한 snake case를 선택하였습니다. 
7. 통일성을 지키도록 수정하겠습니다.
8. not null로 설계했습니다.
9. 기획 수정후 구현 범위를 구체적으로 제한해서 readme에 적용할 계획입니다.

**Comment by f-lab-robert** [comment]
> Member 테이블을 참조할 생각이었는데, 닉네임, 성명 같은 필드가 없으므로 created_by, modifed_by를 id에서 userid로 변경

-> id 와 userid 이렇게 써놓으면 독자 입장에서 헷갈립니다. 문장을 정확하게 써주세요. pk 값 대신에 실제 user 를 식별할 수 있는 user 가 등록한 id 를 등록 이라는 표현이 더 적합해보입니다. 타인의 입장을 고려해야 합니다.

> 주문은 본인이 하는 것이니 member_id가 created_by이며, 주문일자가 곧 created_date라고 생각했습니다. 주문 상태 변경 추적을 위해 modified_date 필드를 추가했습니다.

-> 무슨말인지 전혀 이해가 되지 않습니다. 문장을 다듬어 보시겠어요 ? 느끼기로는 orders table 에 created_date 가 주문일자이기 때문에 필요하다라고 정의하신 것 같은데 공유해주신 테이블에는 없는 것 같습니다. 

> ItemCategory 테이블 : ItemCategory 테이블은 item의 created, modified 정보와는 구분되어야 한다고 생각하여 해당 필드들을 추가했습니다.

-> 저번에 설명해주신 것 처럼 사이즈에 대한 정보를 order 가 같고 있으려면 orders table 에 item & itemDetail 이 모두 관계가 매핑되어 있어야 하는게 아닌가하는 질문입니다. 참고로, 저번에 공유해주신 erd 에서는 item 과 orders 와의 관계가 없었으며 orders 와 itemDetail 하고만 관계가 매핑되어 있었습니다.

> 주문 등은 일자가 아닌 시간에 대한 정보까지 갖고 있어야한다고 생각해서 datetime과 timestamp 중 선택하였는데, 국내 서비스라고 한정하여 datetime을 선택하였습니다.

-> 제가 질문드린건 각기 다른 특성을 알고 있으셨는지 찾아보고 정리하는 것 입니다. 현재 저는 주원님 성권님이 각기 다른 특성을 정확하게 인지하고 있다고 생각하지 않습니다. 국내, 해외 서비스에 따라 둘의 차이가 발생하는건 보이지 않습니다. 어떠한 근거로 이러한 결론을 내리신거죠 ? 성급한 결론의 오류입니다.

> OrderItem - Item : 의미상 주문이 해당 물건(item)을 갖는게 맞다고 판단하는데 주문 item의 사이즈를 알수 없다는 문제점이 있습니다.
> 해결 방안으로 orderItem과 ItemDetail에 관계를 맺는 방법과 OrderItem과 Item이 관계를 맺고 itemDetail과도 관계를 맺는 방법 2가지를 생각해보았습니다. 어떻게 관계를 맺어야할지 판단하기 어려워 약간의 조언을 부탁드리고 싶습니다.

-> 질문이 이런식으로 자주 이어져야 합니다. 위의 코멘트 내용 중에 본 질문에 해당하는 답변을 찾을 수 있으리라 생각합니다. 그럼에도 궁금증이 계속된다면 멘토링 시간에 재차 질의해주세요. 

> 개념적으로는 order이지만 db예약어를 피하기 위해 테이블명을 orders로 결정했습니다. orderitem은 예약어에 걸리지 않으므로 그대로 채택하였습니다.

-> 제가 궁금했던건 orders 와 item table 의 중간 테이블 역할을 하는 것이면 각각의 테이블 명을 사용하는게 더 자연스러워보이지 않나해서 질문드렸던 것 입니다. 항상 "기준" 이라는게 중요하니까요. "A Table 명칭 + B Table 명칭" 이라는 기준이 있으면 ordersItem 이 되어야 하지 않을까요 ? 기준이 어떻게 되는걸까요 ?

> db 필드명은 대소문자 구분을 하지 않기 때문에 camel case보다 필드명을 보고 무슨 정보를 가지는 필드인지 명확하게 표현하기 유리한 snake case를 선택하였습니다.

-> table 명에 대해서는 어떻게 생각하시나요 ?

**Comment by KJW921222** [comment]
1. "중간 테이블은 A 테이블명, B 테이블명을 언더바(_)로 연결한다" 라는 기준을 잡고 수정했습니다.
2. table명은 대소문자를 구분하기 때문에 소문자만을 사용하고 필드 명명 규칙과 통일성을 주기 위해 snake case를 적용했습니다.
3. timestamp가 지원가능한 범위는 '1970-01-01 00:00:01' - '2038-01-19 03:14:07' 이다. 2038년 문제를  고려하여 datetime을 선택했습니다.

이상의 내용들을 Wiki에 정리하도록 하겠습니다.
