### ISSUE TITLE
기획 수정

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/s-mall#12]
[ Context ]
- 작게 제대로 된 서비스를 만든다는 취지에 맞게 기획의 범위를 줄일 필요성이 생겼다. 본 프로젝트는 기획에 방점이 있는게 아닌 작고 제대로된 서비스를 만들어서 배포해보는데 의의가 있다. 제대로 되고 많은 서비스들의 복잡성을 기획하는 건 PM (기획자) 의 업무 역량이다.

[ Ref ]
- 옷의 사이즈 / 색상 등은 90,95,100 등 system 에서 미리 정의해놓은 형태의 select 로만 등록이 가능하다.
- 옷의 대카테고리는 상의,하의 이며 상세 카테코리 또한 3가지를 넘지 않는다.
- 주문을 상세하게 보여주는 페이지는 주문된 옷의 총 가격과 갯수만 보여준다. 옷의 종류에 따라 각각의 세세한 정보, 가령 사이즈, 색상, 가격등은 현 단계에서 고려하지 않는다.

[ Definition of Done ]
- 위의 내용등을 참고해서 기획을 최대한 줄여본다.

**Comment by KJW921222** [comment]
기존에는 상품의 사이즈를 직접 입력하도록 하여 하나의 상품이 너무 많은 사이즈를 가질 수 있었다.
-> 상품 등록 시, 상품의 사이즈는 시스템에서 미리 정의해놓은 값만 선택할 수 있도록 수정하여 기획의 범위를 줄임.

[카카오 오븐 링크](https://ovenapp.io/view/s9dImy0EtGhZLtWVpt5nPa9SQoyRIgoz/)

**Comment by f-lab-robert** [comment]
@KJW921222 링크를 직접 클릭해보시겠어요 ?

**Comment by f-lab-robert** [comment]
issue 는 re-

**Comment by f-lab-robert** [comment]
> 상품 등록 시, 상품의 사이즈는 시스템에서 미리 정의해놓은 값만 선택할 수 있도록 수정.
> 주문 시, 상품의 세세한 정보 (색상 사이즈 등)은 고려하지 않도록 수정.

-> 기존의 문제 혹은 누락 된 사항에 대해 먼저 정의를 한 후, 이렇게 개선 혹은 수정했다로 표현해주시겠어요 ? 처음 이 issue/ticket 을 보는 사람이 왜 이렇게 바뀌었는지 궁금하지 않을까요 ?
