### ISSUE TITLE
README 작성

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/s-mall#13]
- 프로젝트 목표
- 기술 스택
- 서비스 간단 소개글 
- Wiki 에 작성한 내용 중 README ( 프로젝트 소개 단에 ) 에 작성되면 좋을 내용들 작성

**Comment by sunggwon** [comment]
https://github.com/f-lab-edu/s-mall/tree/feature-%2313

**Comment by f-lab-robert** [comment]
@sunggwon  PR 을 날려주시고. PR 을 통해 리뷰를 받아야 겠죠 ?
