### ISSUE TITLE
데이터 베이스 테이블 만들기

### ISSUE THREAD

**Issue by sunggwon** [f-lab-edu/s-mall#14]
[Context]
  데이터 베이스 모델링한 내용으로 데이터베이스 테이블을 만들 필요가 있다.

[Definition of Done]
  GCP에 테이블 작성 완료

**Comment by sunggwon** [comment]
![그림1](https://user-images.githubusercontent.com/17060341/165928946-07d5552c-6b58-4c2c-b89b-db4d64822301.png)

![그림2](https://user-images.githubusercontent.com/17060341/165929049-1f7d82af-04e6-4c5e-9977-67eca64d00c4.png)

다음과 같이 테이블 작성 하였습니다.

확인 부탁드립니다.

**Comment by KJW921222** [comment]
![ERD](https://user-images.githubusercontent.com/89616237/168428632-1932d8ec-cd09-4e9b-a215-fe4b742a4e07.png)

ERD 첨부합니다.
