### ISSUE TITLE
기획 수정

### ISSUE THREAD

**Issue by KJW921222** [f-lab-edu/s-mall#2]
[ 정의 ]
기존 기획의 규모가 크고 기능이 모호해 프로젝트의 목표와 부합하지 않음. 
따라서 프로젝트 목표에 따라 규모를 축소하고 기능을 구체화 할 필요가 생김.

[ 수정 기준 ]
20개 이하의 API 개수를 갖도록 핵심적인 기능 기획

[ 완료 기준 ]
기획한 기능 카카오 오븐에 적용 완료 및 문서화

**Comment by sunggwon** [comment]
- [기존 목표] 보단 [정의]가 더 적절한거 같으며, 조금 더 간결하게 작성돼야 가독성이 좋을거 같습니다.

예를들어 "기존 기획의 규모가 크고 기능이 모호해 프로젝트의 목표와 부합하지 않음. 따라서 프로젝트 목표에 따라 규모를 축소하고 기능을 구체화 할 필요가 생김" 과 같이 간결하게 정의하는게 좋을거 같습니다.

-  수정 기준이 "20개 이하의 API 개수의 기능 기획"과 같이 기준이 명확하였으면 더 좋을거 같습니다. 

-  완료 기준이 "카카오 오븐 수정 완료" 보단 "기획한 API 기능 카카오 오븐에 적용 완료"와 같이 명시적이면 더 명확한 기준이 될거 같습니다.

**Comment by f-lab-robert** [comment]
vcxcvxcvcxv
