### ISSUE TITLE
Git branch 전략 논의 및 선정

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/s-mall#3]
[ Context ]
- Git Flow 를 통해 git branch 의 가장 대중적이고 기본적인 원리를 살펴보았다. 본 서비스에 어떤 git 전략을 통해 브랜치를 관리 할지 정해야 할 필요성이 생겼다.

[ Definition of Done ]
- Git Branch 전략을 상호간에 합의 한후에 Wiki 에 정리한다.

**Comment by sunggwon** [comment]
깃 브랜치 전략을 WIKI에 정리 하였습니다. 확인 부탁드립니다.

https://github.com/f-lab-edu/s-mall/wiki/Git-%EC%A0%84%EB%9E%B5

**Comment by sunggwon** [comment]
저희가 선정한 Git 전략에 대해 Wiki에 해당 Git 전략 방법 및 선정 이유에 대해 정리해놨습니다. 확인 부탁드리겠습니다.
