### ISSUE TITLE
데이터 베이스 회원 member 삽입

### ISSUE THREAD

**Issue by sunggwon** [f-lab-edu/s-mall#30]
[ Context ]

서비스 기능 구현 테스트를 위해 member 테이블에 sql에 각 member 타입 (User와 Admin)인 컬럼을 넣을 필요가 생겼다.

[ Definition of Done ]
User 타입의 member와 Admin타입의 member를 gcp의 small 데이터 베이스에 삽입한다.

**Comment by sunggwon** [comment]
![issues-30](https://user-images.githubusercontent.com/17060341/166126125-e0cc6010-9bec-46d0-a5b0-520f76425c2f.png)

삽입 완료 했습니다. 검토 부탁드립니다.

**Comment by f-lab-robert** [comment]
@sunggwon 멘토링 시간에 말씀드린 하단의 내용들 참고해주세요

- modified_date 를 regist_date 와 동일하게 초기 값 셋팅
- password 부분 규약에 맞는 형태로 변경 ( 추후 암호화 해서 진행해야 함 ) 

위의 부분 업뎃 후에 티켓 닫아주세요.

**Comment by sunggwon** [comment]
@f-lab-robert 변경완료 했습니다.

![image](https://user-images.githubusercontent.com/17060341/168529274-90d5fd6d-9a2e-4a62-8839-777fcf57f1c8.png)
