### ISSUE TITLE
프로젝트 세팅

### ISSUE THREAD

**Issue by KJW921222** [f-lab-edu/s-mall#31]
[ Context ]
애플리케이션의 개발을 위해 필요한 의존성을 추가하고, db 및 mybatis를 세팅할 필요가 있다.

[ Definition of Done ]
build.gradle 에 필요한 의존성을 추가하고, 의존성의 추가 이유와 관련 내용을 WIki에 기술한다.
application.yml에 db, mybatis를 세팅하고 db와 연결이 되는지 테스트해본다.

**Comment by sunggwon** [comment]
다음과 같은 의존성을 추가로 지정할 계획입니다.

- web
  - Spring MVC 및 Jackson 등을 포함하며, 내장 톰캣을 기본 컨테이너로 사용한다. 

- validation
  - 밸리데이션 체크를 위한 의존성
  - 스프링부트 2.3 부터 Spring Web 의존성에 포함되어 있던 validation이 제거됨에 따라, 따로 의존성을 추가해준다.

- security
  - 스프링 하위 프레임워크로서, 스프링 기반 애플리케이션의 보안(인증 및 인가, 권한부여 등)을 담당한다.
  - webflux를 사용하는 reactive 애플리케이션이 아닌, 일반적인 서블릿 애플리케이션에서는 서블릿 필터를 사용한다. 

- devtools
  - 개발의 편의를 위한 의존성이다.
  - 소스의 변경 시 애플리케이션을 재시작하지 않아도 변경사항을 적용시켜 확인할 수 있다.

- lombok
  - 어노테이션 기반으로 반복되는 행위를 자동으로 작성해준다.
  - 컴파일 타임에 바이트코드를 변환하는 방식으로 동작하고, 그러므로 compileOnly 속성을 가진다.

- mybatis
  - Java Persistence Framework의 하나로, SQL Mapper를 통해 쿼리와 자바 코드를 분리하고, 자바 객체(DAO)와 매핑한다.

- mariadb
  - 사용하는 데이터베이스
  - DB 의존성은 런타임에나 필요하므로, runtimeOnly 속성을 가진다.
