### ISSUE TITLE
데이터 베이스 설계 논의 및 정의

### ISSUE THREAD

**Issue by sunggwon** [f-lab-edu/s-mall#6]
[정의]
서비스에 적용하기 위해 각자 정의한 데이터베이스를 최종적으로 통합할 필요가 있다.

[완료 기준]
상호 협의된 데이터 베이스 ERD를  Wiki에 작성

**Comment by KJW921222** [comment]
https://www.erdcloud.com/d/pGTMqeeDb54xjn7nj
