### ISSUE TITLE
API 기능 논의 및 정의

### ISSUE THREAD

**Issue by sunggwon** [f-lab-edu/s-mall#7]
[정의]
서비스에 적용하기 위해 각자 정의한 API를 통합할 필요가 있다.

[완료 기준]
상호 협의된 API 명세서 Wiki에 작성 완료

**Comment by KJW921222** [comment]
https://github.com/f-lab-edu/s-mall/wiki/API-%EB%AA%85%EC%84%B8%EC%84%9C
